//! Audit sink trait seam.
//!
//! VSR audit events are:
//! - **Append-only.** Events are never updated or deleted.
//! - **Transactional with the row they describe.** A CRUD event is written in
//!   the same database transaction as the mutation it records.
//! - **Never silently dropped.** If the sink cannot accept an event, the
//!   calling operation fails rather than proceeding unaudited.
//!
//! # Key traits
//!
//! | Trait | Purpose |
//! |---|---|
//! | [`AuditSink`] | Write and flush audit events |
//!
//! # Default implementation
//!
//! The default `DbAuditSink` writes events to `_vsr_audit_events` in the
//! same database as the application data. Future sinks (append-only log
//! files, external SIEM) implement this trait.

use std::{collections::HashMap, future::Future};
use vsr_core::error::VsrResult;

// ─── AuditEvent ───────────────────────────────────────────────────────────────

/// The category of an auditable operation.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum AuditEventKind {
    /// A resource record was created.
    RecordCreated,
    /// A resource record was updated.
    RecordUpdated,
    /// A resource record was deleted.
    RecordDeleted,
    /// A user logged in.
    UserLogin,
    /// A login attempt failed.
    LoginFailed,
    /// A user logged out.
    UserLogout,
    /// A new user account was created.
    UserCreated,
    /// A user account was deleted.
    UserDeleted,
    /// A password was changed.
    PasswordChanged,
    /// An authz grant was created.
    GrantCreated,
    /// An authz grant was revoked.
    GrantRevoked,
    /// An authz check was denied.
    AccessDenied,
    /// A backup completed successfully.
    BackupCompleted,
    /// A backup restore was verified.
    BackupVerified,
    /// A custom event defined by the operator.
    Custom(String),
}

impl std::fmt::Display for AuditEventKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            AuditEventKind::RecordCreated => "record.created",
            AuditEventKind::RecordUpdated => "record.updated",
            AuditEventKind::RecordDeleted => "record.deleted",
            AuditEventKind::UserLogin => "user.login",
            AuditEventKind::LoginFailed => "user.login_failed",
            AuditEventKind::UserLogout => "user.logout",
            AuditEventKind::UserCreated => "user.created",
            AuditEventKind::UserDeleted => "user.deleted",
            AuditEventKind::PasswordChanged => "user.password_changed",
            AuditEventKind::GrantCreated => "authz.grant_created",
            AuditEventKind::GrantRevoked => "authz.grant_revoked",
            AuditEventKind::AccessDenied => "authz.access_denied",
            AuditEventKind::BackupCompleted => "backup.completed",
            AuditEventKind::BackupVerified => "backup.verified",
            AuditEventKind::Custom(s) => s.as_str(),
        };
        f.write_str(s)
    }
}

/// A single auditable event.
///
/// Events are immutable after construction. The sink is responsible for
/// assigning a stable ID and persisted timestamp if not already set.
#[derive(Debug, Clone)]
pub struct AuditEvent {
    /// Unique event ID (UUID v4 or similar). Generated by the caller.
    pub id: String,
    /// What happened.
    pub kind: AuditEventKind,
    /// When it happened (Unix timestamp, UTC).
    pub timestamp: i64,
    /// The user who performed the action. `None` for anonymous/system events.
    pub actor_id: Option<String>,
    /// The resource type affected (e.g. `"Post"`, `"Invoice"`).
    pub resource_name: Option<String>,
    /// The ID of the affected resource record.
    pub resource_id: Option<String>,
    /// Additional structured context (safe to log — must not contain secrets).
    pub metadata: HashMap<String, serde_json::Value>,
    /// Request ID linking this event to a specific HTTP request.
    pub request_id: Option<String>,
}

impl AuditEvent {
    /// Minimal constructor. Use the builder methods to add optional fields.
    pub fn new(id: String, kind: AuditEventKind, timestamp: i64) -> Self {
        Self {
            id,
            kind,
            timestamp,
            actor_id: None,
            resource_name: None,
            resource_id: None,
            metadata: HashMap::new(),
            request_id: None,
        }
    }

    /// Attach an actor user ID.
    pub fn with_actor(mut self, actor_id: impl Into<String>) -> Self {
        self.actor_id = Some(actor_id.into());
        self
    }

    /// Attach the resource that was affected.
    pub fn with_resource(
        mut self,
        resource_name: impl Into<String>,
        resource_id: impl Into<String>,
    ) -> Self {
        self.resource_name = Some(resource_name.into());
        self.resource_id = Some(resource_id.into());
        self
    }

    /// Attach a request ID for correlation.
    pub fn with_request_id(mut self, request_id: impl Into<String>) -> Self {
        self.request_id = Some(request_id.into());
        self
    }

    /// Add a metadata field. Value must be JSON-serializable.
    pub fn with_meta(
        mut self,
        key: impl Into<String>,
        value: impl serde::Serialize,
    ) -> Self {
        if let Ok(v) = serde_json::to_value(value) {
            self.metadata.insert(key.into(), v);
        }
        self
    }
}

// ─── AuditSink trait ──────────────────────────────────────────────────────────

/// Accepts and persists audit events.
///
/// # Contract
///
/// - `record` MUST be called inside the same database transaction as the
///   mutation being audited (for the default DB sink). The sink handles this
///   via the connection it holds.
/// - If `record` returns `Err`, the calling operation MUST roll back its
///   transaction and return an error to the client.
/// - `flush` drains any buffered events to permanent storage. Called at
///   graceful shutdown.
pub trait AuditSink: Send + Sync + 'static {
    /// Record a single audit event.
    ///
    /// For the default DB sink, this must be called while a transaction is
    /// open; the event is written within that transaction.
    fn record(&self, event: AuditEvent) -> impl Future<Output = VsrResult<()>> + Send;

    /// Flush any buffered events to permanent storage.
    fn flush(&self) -> impl Future<Output = VsrResult<()>> + Send;
}
