-- Generated by very_simple_rest for runtime authorization assignments.

CREATE TABLE authz_scoped_assignment (
id TEXT PRIMARY KEY,
user_id INTEGER NOT NULL,
created_by_user_id INTEGER,
created_at TEXT NOT NULL,
expires_at TEXT,
target_kind TEXT NOT NULL,
target_name TEXT NOT NULL,
scope_name TEXT NOT NULL,
scope_value TEXT NOT NULL
);

CREATE INDEX idx_authz_scoped_assignment_user ON authz_scoped_assignment (user_id);
CREATE INDEX idx_authz_scoped_assignment_scope ON authz_scoped_assignment (scope_name, scope_value);

CREATE TABLE authz_scoped_assignment_event (
id TEXT PRIMARY KEY,
assignment_id TEXT NOT NULL,
user_id INTEGER NOT NULL,
created_by_user_id INTEGER,
created_at TEXT NOT NULL,
event_kind TEXT NOT NULL,
target_kind TEXT NOT NULL,
target_name TEXT NOT NULL,
scope_name TEXT NOT NULL,
scope_value TEXT NOT NULL,
expires_at TEXT,
reason TEXT
);

CREATE INDEX idx_authz_scoped_assignment_event_user ON authz_scoped_assignment_event (user_id, created_at);
CREATE INDEX idx_authz_scoped_assignment_event_assignment ON authz_scoped_assignment_event (assignment_id, created_at);
