-- Generated by very_simple_rest. Review before applying.

CREATE TABLE family (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    owner_user_id INTEGER NOT NULL,
    slug TEXT NOT NULL,
    name TEXT NOT NULL,
    timezone TEXT NOT NULL
);

CREATE INDEX idx_family_owner_user_id ON family (owner_user_id);

CREATE TABLE household (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    family_id INTEGER NOT NULL,
    created_by_user_id INTEGER NOT NULL,
    slug TEXT NOT NULL,
    label TEXT NOT NULL,
    timezone TEXT NOT NULL,
    FOREIGN KEY (family_id) REFERENCES family(id)
);

CREATE INDEX idx_household_created_by_user_id ON household (created_by_user_id);

CREATE INDEX idx_household_family_id ON household (family_id);

CREATE TABLE family_member (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    family_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    created_by_user_id INTEGER NOT NULL,
    role_label TEXT NOT NULL,
    display_name TEXT NOT NULL,
    is_child BOOLEAN NOT NULL,
    FOREIGN KEY (family_id) REFERENCES family(id)
);

CREATE INDEX idx_family_member_created_by_user_id ON family_member (created_by_user_id);

CREATE INDEX idx_family_member_family_id ON family_member (family_id);

CREATE INDEX idx_family_member_user_id ON family_member (user_id);

CREATE TABLE family_delegate (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    family_id INTEGER NOT NULL,
    primary_user_id INTEGER NOT NULL,
    delegate_user_id INTEGER NOT NULL,
    label TEXT NOT NULL,
    FOREIGN KEY (family_id) REFERENCES family(id)
);

CREATE INDEX idx_family_delegate_delegate_user_id ON family_delegate (delegate_user_id);

CREATE INDEX idx_family_delegate_family_id ON family_delegate (family_id);

CREATE INDEX idx_family_delegate_primary_user_id ON family_delegate (primary_user_id);

CREATE TABLE child_profile (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    family_id INTEGER NOT NULL,
    household_id INTEGER NOT NULL,
    created_by_user_id INTEGER NOT NULL,
    primary_guardian_user_id INTEGER NOT NULL,
    display_name TEXT NOT NULL,
    school TEXT NOT NULL,
    pickup_code TEXT,
    FOREIGN KEY (family_id) REFERENCES family(id),
    FOREIGN KEY (household_id) REFERENCES household(id)
);

CREATE INDEX idx_child_profile_created_by_user_id ON child_profile (created_by_user_id);

CREATE INDEX idx_child_profile_family_id ON child_profile (family_id);

CREATE INDEX idx_child_profile_household_id ON child_profile (household_id);

CREATE INDEX idx_child_profile_primary_guardian_user_id ON child_profile (primary_guardian_user_id);

CREATE TABLE care_plan (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    family_id INTEGER NOT NULL,
    child_profile_id INTEGER NOT NULL,
    author_user_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    support_visible BOOLEAN NOT NULL,
    notes TEXT NOT NULL,
    FOREIGN KEY (family_id) REFERENCES family(id),
    FOREIGN KEY (child_profile_id) REFERENCES child_profile(id)
);

CREATE INDEX idx_care_plan_author_user_id ON care_plan (author_user_id);

CREATE INDEX idx_care_plan_child_profile_id ON care_plan (child_profile_id);

CREATE INDEX idx_care_plan_family_id ON care_plan (family_id);

CREATE INDEX idx_care_plan_support_visible ON care_plan (support_visible);

CREATE TABLE guardian_note (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    family_id INTEGER NOT NULL,
    child_profile_id INTEGER NOT NULL,
    author_user_id INTEGER NOT NULL,
    category TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (family_id) REFERENCES family(id),
    FOREIGN KEY (child_profile_id) REFERENCES child_profile(id)
);

CREATE INDEX idx_guardian_note_author_user_id ON guardian_note (author_user_id);

CREATE INDEX idx_guardian_note_child_profile_id ON guardian_note (child_profile_id);

CREATE INDEX idx_guardian_note_family_id ON guardian_note (family_id);

CREATE TABLE household_announcement (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    family_id INTEGER NOT NULL,
    author_user_id INTEGER NOT NULL,
    household_slug TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL
);

CREATE INDEX idx_household_announcement_author_user_id ON household_announcement (author_user_id);

CREATE INDEX idx_household_announcement_family_id ON household_announcement (family_id);

CREATE INDEX idx_household_announcement_household_slug ON household_announcement (household_slug);

CREATE TABLE shopping_item (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    family_id INTEGER NOT NULL,
    household_id INTEGER NOT NULL,
    created_by_user_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    completed BOOLEAN NOT NULL,
    FOREIGN KEY (family_id) REFERENCES family(id),
    FOREIGN KEY (household_id) REFERENCES household(id)
);

CREATE INDEX idx_shopping_item_created_by_user_id ON shopping_item (created_by_user_id);

CREATE INDEX idx_shopping_item_family_id ON shopping_item (family_id);

CREATE INDEX idx_shopping_item_household_id ON shopping_item (household_id);

CREATE TABLE calendar_event (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    family_id INTEGER NOT NULL,
    household_id INTEGER NOT NULL,
    created_by_user_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    starts_at TEXT NOT NULL,
    ends_at TEXT NOT NULL,
    FOREIGN KEY (family_id) REFERENCES family(id),
    FOREIGN KEY (household_id) REFERENCES household(id)
);

CREATE INDEX idx_calendar_event_created_by_user_id ON calendar_event (created_by_user_id);

CREATE INDEX idx_calendar_event_family_id ON calendar_event (family_id);

CREATE INDEX idx_calendar_event_household_id ON calendar_event (household_id);
