use std::collections::{BTreeMap, BTreeSet, HashMap};

use proc_macro2::Span;

use super::model::{
    GeneratedValue, ResourceSpec, RowPolicies, ServiceSpec, is_optional_type, temporal_scalar_kind,
};

#[derive(Clone, Debug, Eq, PartialEq)]
struct RenderedIndex {
    name: String,
    fields: Vec<String>,
    unique: bool,
}

pub fn render_service_migration_sql(service: &ServiceSpec) -> syn::Result<String> {
    let ordered_resources = topologically_sorted_resources(service)?;
    let exists_target_indexes = exists_target_index_fields(service);
    let mut statements = Vec::new();

    for resource in ordered_resources {
        statements.push(render_create_table_sql(resource));
        statements.extend(render_index_sql(
            resource,
            exists_target_indexes.get(&resource.table_name),
        ));
    }

    let body = statements.join("\n\n");

    Ok(format!(
        "-- Generated by very_simple_rest. Review before applying.\n\n{body}\n"
    ))
}

pub fn render_service_diff_migration_sql(
    previous: &ServiceSpec,
    next: &ServiceSpec,
) -> syn::Result<String> {
    let previous_resources = previous
        .resources
        .iter()
        .map(|resource| (resource.table_name.as_str(), resource))
        .collect::<HashMap<_, _>>();
    let next_order = topologically_sorted_resources(next)?;
    let previous_exists_target_indexes = exists_target_index_fields(previous);
    let next_exists_target_indexes = exists_target_index_fields(next);
    let mut statements = Vec::new();

    for resource in next_order {
        match previous_resources.get(resource.table_name.as_str()) {
            Some(previous_resource) => {
                statements.extend(render_resource_diff_sql(
                    previous_resource,
                    resource,
                    previous_exists_target_indexes.get(previous_resource.table_name.as_str()),
                    next_exists_target_indexes.get(resource.table_name.as_str()),
                )?);
            }
            None => {
                statements.push(render_create_table_sql(resource));
                statements.extend(render_index_sql(
                    resource,
                    next_exists_target_indexes.get(&resource.table_name),
                ));
            }
        }
    }

    for previous_resource in &previous.resources {
        if next
            .resources
            .iter()
            .all(|resource| resource.table_name != previous_resource.table_name)
        {
            return Err(syn::Error::new(
                previous_resource.struct_ident.span(),
                format!(
                    "table `{}` exists in the previous schema but not in the next schema; destructive migration must be written manually",
                    previous_resource.table_name
                ),
            ));
        }
    }

    if statements.is_empty() {
        return Ok("-- No additive schema changes detected.\n".to_owned());
    }

    let body = statements.join("\n\n");
    Ok(format!(
        "-- Generated by very_simple_rest. Review before applying.\n\n{body}\n"
    ))
}

fn topologically_sorted_resources(service: &ServiceSpec) -> syn::Result<Vec<&ResourceSpec>> {
    #[derive(Clone, Copy, Eq, PartialEq)]
    enum VisitState {
        Visiting,
        Done,
    }

    fn visit<'a>(
        resource: &'a ResourceSpec,
        resource_map: &HashMap<&'a str, &'a ResourceSpec>,
        states: &mut HashMap<&'a str, VisitState>,
        ordered: &mut Vec<&'a ResourceSpec>,
    ) -> syn::Result<()> {
        let table_name = resource.table_name.as_str();
        match states.get(table_name) {
            Some(VisitState::Done) => return Ok(()),
            Some(VisitState::Visiting) => {
                return Err(syn::Error::new(
                    Span::call_site(),
                    format!(
                        "cyclic relation dependency detected while ordering migration for `{table_name}`"
                    ),
                ));
            }
            None => {}
        }

        states.insert(table_name, VisitState::Visiting);

        let mut dependencies = BTreeSet::new();
        for field in &resource.fields {
            if let Some(relation) = &field.relation {
                let referenced_table = relation.references_table.as_str();
                if resource_map.contains_key(referenced_table) {
                    dependencies.insert(referenced_table);
                }
            }
        }

        for dependency in dependencies {
            let dependency_resource = resource_map
                .get(dependency)
                .expect("dependency exists in resource map");
            visit(dependency_resource, resource_map, states, ordered)?;
        }

        states.insert(table_name, VisitState::Done);
        ordered.push(resource);
        Ok(())
    }

    let resource_map = service
        .resources
        .iter()
        .map(|resource| (resource.table_name.as_str(), resource))
        .collect::<HashMap<_, _>>();
    let mut states = HashMap::new();
    let mut ordered = Vec::with_capacity(service.resources.len());

    for resource in &service.resources {
        visit(resource, &resource_map, &mut states, &mut ordered)?;
    }

    Ok(ordered)
}

fn render_create_table_sql(resource: &ResourceSpec) -> String {
    let mut definitions = resource
        .fields
        .iter()
        .map(|field| render_field_definition(resource, field))
        .collect::<Vec<_>>();

    definitions.extend(resource.fields.iter().filter_map(|field| {
        field.relation.as_ref().map(|relation| {
            let on_delete = relation
                .on_delete
                .map(|action| format!(" ON DELETE {}", action.sql()))
                .unwrap_or_default();
            format!(
                "FOREIGN KEY ({}) REFERENCES {}({}){}",
                field.name(),
                relation.references_table,
                relation.references_field,
                on_delete
            )
        })
    }));

    format!(
        "CREATE TABLE {} (\n    {}\n);",
        resource.table_name,
        definitions.join(",\n    ")
    )
}

fn render_resource_diff_sql(
    previous: &ResourceSpec,
    next: &ResourceSpec,
    previous_extra_index_fields: Option<&BTreeSet<String>>,
    next_extra_index_fields: Option<&BTreeSet<String>>,
) -> syn::Result<Vec<String>> {
    let previous_fields = previous
        .fields
        .iter()
        .map(|field| (field.name(), field))
        .collect::<HashMap<_, _>>();
    let next_indexes = rendered_indexes(next, next_extra_index_fields);
    let previous_indexes = rendered_indexes(previous, previous_extra_index_fields);
    let mut statements = Vec::new();

    if previous.id_field != next.id_field || previous.db != next.db {
        return Err(syn::Error::new(
            next.struct_ident.span(),
            format!(
                "resource `{}` changed database backend or id field; write a manual migration",
                next.table_name
            ),
        ));
    }

    for previous_field in &previous.fields {
        if next.find_field(&previous_field.name()).is_none() {
            return Err(syn::Error::new(
                next.struct_ident.span(),
                format!(
                    "field `{}` was removed from `{}`; destructive migration must be written manually",
                    previous_field.name(),
                    next.table_name
                ),
            ));
        }
    }

    for next_field in &next.fields {
        let field_name = next_field.name();
        match previous_fields.get(&field_name) {
            Some(previous_field) => validate_compatible_field(previous_field, next_field, next)?,
            None => statements.push(render_add_column_sql(next, next_field)?),
        }
    }

    for (name, index) in &previous_indexes {
        if index.unique && !next_indexes.contains_key(name) {
            return Err(syn::Error::new(
                next.struct_ident.span(),
                format!(
                    "unique index `{name}` was removed or changed on `{}`; write a manual migration",
                    next.table_name
                ),
            ));
        }
    }

    for (name, index) in &next_indexes {
        if !previous_indexes.contains_key(name) {
            statements.push(render_index_statement(next, index));
        }
    }

    Ok(statements)
}

fn render_field_definition(resource: &ResourceSpec, field: &super::model::FieldSpec) -> String {
    let field_name = field.name();

    if field.is_id {
        return resource.db.primary_key_sql(&field_name);
    }

    let nullability = if is_optional_type(&field.ty) {
        ""
    } else {
        " NOT NULL"
    };

    match field.generated {
        GeneratedValue::CreatedAt | GeneratedValue::UpdatedAt => {
            format!(
                "{} {} NOT NULL DEFAULT {}",
                field_name,
                field.sql_type,
                resource
                    .db
                    .generated_temporal_expression(temporal_scalar_kind(&field.ty))
            )
        }
        GeneratedValue::None | GeneratedValue::AutoIncrement => {
            format!("{} {}{}", field_name, field.sql_type, nullability)
        }
    }
}

fn render_add_column_sql(
    resource: &ResourceSpec,
    field: &super::model::FieldSpec,
) -> syn::Result<String> {
    if field.is_id {
        return Err(syn::Error::new(
            resource.struct_ident.span(),
            format!(
                "adding a new id field to `{}` is not supported by additive migration generation",
                resource.table_name
            ),
        ));
    }

    if field.relation.is_some() {
        return Err(syn::Error::new(
            resource.struct_ident.span(),
            format!(
                "adding relation field `{}` to `{}` requires a manual migration",
                field.name(),
                resource.table_name
            ),
        ));
    }

    let nullability_safe = is_optional_type(&field.ty)
        || matches!(
            field.generated,
            GeneratedValue::CreatedAt | GeneratedValue::UpdatedAt
        );
    if !nullability_safe {
        return Err(syn::Error::new(
            resource.struct_ident.span(),
            format!(
                "adding required field `{}` to `{}` requires a manual migration with backfill",
                field.name(),
                resource.table_name
            ),
        ));
    }

    Ok(format!(
        "ALTER TABLE {} ADD COLUMN {};",
        resource.table_name,
        render_field_definition(resource, field)
    ))
}

fn render_index_sql(
    resource: &ResourceSpec,
    extra_index_fields: Option<&BTreeSet<String>>,
) -> Vec<String> {
    rendered_indexes(resource, extra_index_fields)
        .into_values()
        .map(|index| render_index_statement(resource, &index))
        .collect()
}

fn render_index_statement(resource: &ResourceSpec, index: &RenderedIndex) -> String {
    let unique = if index.unique { "UNIQUE " } else { "" };
    format!(
        "CREATE {unique}INDEX {} ON {} ({});",
        index.name,
        resource.table_name,
        index.fields.join(", ")
    )
}

fn rendered_indexes(
    resource: &ResourceSpec,
    extra_index_fields: Option<&BTreeSet<String>>,
) -> BTreeMap<String, RenderedIndex> {
    let mut indexed = BTreeMap::new();

    for field in &resource.fields {
        if field.relation.is_some() {
            insert_index(
                &mut indexed,
                resource,
                vec![field.name()],
                false,
            );
        }
        if field.unique {
            insert_index(
                &mut indexed,
                resource,
                vec![field.name()],
                true,
            );
        }
    }

    for field_name in policy_index_fields(&resource.policies) {
        insert_index(&mut indexed, resource, vec![field_name], false);
    }
    if let Some(extra_index_fields) = extra_index_fields {
        for field_name in extra_index_fields {
            insert_index(&mut indexed, resource, vec![field_name.clone()], false);
        }
    }
    for index in &resource.indexes {
        insert_index(&mut indexed, resource, index.fields.clone(), index.unique);
    }

    indexed.retain(|_, index| !(index.fields.len() == 1 && index.fields[0] == resource.id_field));
    indexed
}

fn insert_index(
    indexed: &mut BTreeMap<String, RenderedIndex>,
    resource: &ResourceSpec,
    fields: Vec<String>,
    unique: bool,
) {
    let spec = super::model::IndexSpec { fields, unique };
    let name = spec.name_for_table(resource.table_name.as_str());
    indexed.entry(name.clone()).or_insert(RenderedIndex {
        name,
        fields: spec.fields,
        unique: spec.unique,
    });
}

fn policy_index_fields(policies: &RowPolicies) -> BTreeSet<String> {
    policies
        .controlled_filter_fields()
        .into_iter()
        .chain(
            policies
                .iter_assignments()
                .map(|(_, policy)| policy.field.clone()),
        )
        .collect()
}

fn exists_target_index_fields(service: &ServiceSpec) -> HashMap<String, BTreeSet<String>> {
    let mut indexed = HashMap::<String, BTreeSet<String>>::new();

    for resource in &service.resources {
        for (target_resource, field_name) in resource.policies.exists_index_targets() {
            let Some(target_table) =
                resolve_exists_target_table(&service.resources, &target_resource)
            else {
                continue;
            };
            indexed
                .entry(target_table.to_owned())
                .or_default()
                .insert(field_name);
        }
    }

    indexed
}

fn resolve_exists_target_table<'a>(
    resources: &'a [ResourceSpec],
    target_resource: &str,
) -> Option<&'a str> {
    resources
        .iter()
        .find(|resource| {
            resource.table_name == target_resource
                || resource.struct_ident.to_string() == target_resource
        })
        .map(|resource| resource.table_name.as_str())
}

fn validate_compatible_field(
    previous: &super::model::FieldSpec,
    next: &super::model::FieldSpec,
    resource: &ResourceSpec,
) -> syn::Result<()> {
    let field_name = next.name();
    let changed = previous.sql_type != next.sql_type
        || previous.is_id != next.is_id
        || previous.generated != next.generated
        || previous.relation != next.relation
        || is_optional_type(&previous.ty) != is_optional_type(&next.ty);

    if changed {
        return Err(syn::Error::new(
            resource.struct_ident.span(),
            format!(
                "field `{field_name}` on `{}` changed type, nullability, generation, or relation; write a manual migration",
                resource.table_name
            ),
        ));
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        path::PathBuf,
        time::{SystemTime, UNIX_EPOCH},
    };

    use super::{render_service_diff_migration_sql, render_service_migration_sql};
    use crate::compiler::eon_parser::load_service_from_path;

    fn fixture_path(name: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures")
            .join(name)
    }

    fn example_path(name: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/sqlite_bench")
            .join(name)
    }

    fn policy_example_path(name: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/fine_grained_policies")
            .join(name)
    }

    fn temp_schema_path(name: &str) -> PathBuf {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time should be valid")
            .as_nanos();
        std::env::temp_dir().join(format!("{name}_{stamp}.eon"))
    }

    #[test]
    fn migration_sql_orders_relations_and_emits_indexes() {
        let loaded =
            load_service_from_path(&fixture_path("blog_api.eon")).expect("fixture should parse");
        let sql =
            render_service_migration_sql(&loaded.service).expect("migration sql should render");

        let post_pos = sql
            .find("CREATE TABLE post")
            .expect("post table should exist");
        let comment_pos = sql
            .find("CREATE TABLE comment")
            .expect("comment table should exist");
        assert!(
            post_pos < comment_pos,
            "post table should be created before comment"
        );
        assert!(sql.contains("FOREIGN KEY (post_id) REFERENCES post(id)"));
        assert!(sql.contains("CREATE INDEX idx_comment_post_id ON comment (post_id);"));
    }

    #[test]
    fn migration_sql_indexes_policy_fields() {
        let loaded =
            load_service_from_path(&fixture_path("tenant_api.eon")).expect("fixture should parse");
        let sql =
            render_service_migration_sql(&loaded.service).expect("migration sql should render");

        assert!(sql.contains("CREATE INDEX idx_tenant_post_user_id ON tenant_post (user_id);"));
        assert!(sql.contains("CREATE INDEX idx_tenant_post_tenant_id ON tenant_post (tenant_id);"));
    }

    #[test]
    fn migration_sql_indexes_exists_target_fields() {
        let loaded = load_service_from_path(&fixture_path("exists_policy_api.eon"))
            .expect("fixture should parse");
        let sql =
            render_service_migration_sql(&loaded.service).expect("migration sql should render");

        assert!(sql.contains("CREATE INDEX idx_shared_doc_family_id ON shared_doc (family_id);"));
        assert!(
            sql.contains("CREATE INDEX idx_family_member_family_id ON family_member (family_id);")
        );
        assert!(sql.contains("CREATE INDEX idx_family_member_user_id ON family_member (user_id);"));
    }

    #[test]
    fn migration_sql_renders_declared_unique_and_composite_indexes() {
        let loaded = load_service_from_path(&fixture_path("unique_indexes_api.eon"))
            .expect("fixture should parse");
        let sql =
            render_service_migration_sql(&loaded.service).expect("migration sql should render");

        assert!(sql.contains("CREATE UNIQUE INDEX uidx_workspace_slug ON workspace (slug);"));
        assert!(
            sql.contains(
                "CREATE UNIQUE INDEX uidx_workspace_tenant_id_slug ON workspace (tenant_id, slug);"
            )
        );
        assert!(
            sql.contains(
                "CREATE INDEX idx_workspace_status_published_at ON workspace (status, published_at);"
            )
        );
    }

    #[test]
    fn migration_sql_expands_mixin_fields_and_indexes() {
        let loaded = load_service_from_path(&fixture_path("mixin_fields_api.eon"))
            .expect("fixture should parse");
        let sql =
            render_service_migration_sql(&loaded.service).expect("migration sql should render");

        assert!(sql.contains("created_at TEXT NOT NULL DEFAULT"));
        assert!(sql.contains("updated_at TEXT NOT NULL DEFAULT"));
        assert!(sql.contains("tenant_id INTEGER NOT NULL"));
        assert!(sql.contains("slug TEXT NOT NULL"));
        assert!(sql.contains("CREATE UNIQUE INDEX uidx_post_slug ON post (slug);"));
        assert!(sql.contains("CREATE UNIQUE INDEX uidx_post_tenant_id_slug ON post (tenant_id, slug);"));
    }

    #[test]
    fn migration_sql_renders_on_delete_action_for_relations() {
        let loaded =
            load_service_from_path(&fixture_path("cascade_api.eon")).expect("fixture should parse");
        let sql =
            render_service_migration_sql(&loaded.service).expect("migration sql should render");

        assert!(sql.contains("FOREIGN KEY (parent_id) REFERENCES parent(id) ON DELETE CASCADE"));
    }

    #[test]
    fn migration_sql_renders_datetime_columns_with_sqlite_utc_defaults() {
        let loaded = load_service_from_path(&fixture_path("datetime_api.eon"))
            .expect("fixture should parse");
        let sql =
            render_service_migration_sql(&loaded.service).expect("migration sql should render");

        assert!(sql.contains("starts_at TEXT NOT NULL"));
        assert!(sql.contains(
            "created_at TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%f000+00:00', 'now'))"
        ));
        assert!(sql.contains(
            "updated_at TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%f000+00:00', 'now'))"
        ));
    }

    #[test]
    fn mysql_migration_sql_uses_bigint_foreign_keys_and_varchar_strings() {
        let schema_path = temp_schema_path("mysql_family_migration");
        fs::write(
            &schema_path,
            r#"module: "mysql_family"
db: "Mysql"
resources: [
    {
        name: "Family"
        fields: [
            { name: "id", type: I64, id: true }
            { name: "slug", type: String }
        ]
    }
    {
        name: "FamilyMember"
        fields: [
            { name: "id", type: I64, id: true }
            {
                name: "family_id"
                type: I64
                relation: { references: "family.id" }
            }
            { name: "display_name", type: String }
        ]
    }
]
"#,
        )
        .expect("schema should be written");

        let loaded = load_service_from_path(&schema_path).expect("schema should parse");
        let sql =
            render_service_migration_sql(&loaded.service).expect("migration sql should render");

        assert!(sql.contains("slug VARCHAR(255) NOT NULL"));
        assert!(sql.contains("family_id BIGINT NOT NULL"));

        let _ = fs::remove_file(schema_path);
    }

    #[test]
    fn diff_sql_emits_new_table_and_safe_column_additions() {
        let previous =
            load_service_from_path(&fixture_path("owned_api.eon")).expect("fixture should parse");
        let next = load_service_from_path(&fixture_path("owned_api_v2.eon"))
            .expect("fixture should parse");
        let sql = render_service_diff_migration_sql(&previous.service, &next.service)
            .expect("diff sql should render");

        assert!(sql.contains("ALTER TABLE owned_post ADD COLUMN subtitle TEXT;"));
        assert!(sql.contains("CREATE TABLE audit_log"));
        assert!(sql.contains("CREATE INDEX idx_audit_log_user_id ON audit_log (user_id);"));
    }

    #[test]
    fn diff_sql_adds_exists_target_indexes_for_existing_resources() {
        let previous = load_service_from_path(&fixture_path("exists_policy_api_previous.eon"))
            .expect("fixture should parse");
        let next = load_service_from_path(&fixture_path("exists_policy_api.eon"))
            .expect("fixture should parse");
        let sql = render_service_diff_migration_sql(&previous.service, &next.service)
            .expect("diff sql should render");

        assert!(sql.contains("CREATE INDEX idx_shared_doc_family_id ON shared_doc (family_id);"));
        assert!(
            sql.contains("CREATE INDEX idx_family_member_family_id ON family_member (family_id);")
        );
        assert!(sql.contains("CREATE INDEX idx_family_member_user_id ON family_member (user_id);"));
    }

    #[test]
    fn diff_sql_rejects_destructive_column_changes() {
        let previous =
            load_service_from_path(&fixture_path("owned_api.eon")).expect("fixture should parse");
        let next = load_service_from_path(&fixture_path("owned_api_breaking.eon"))
            .expect("fixture should parse");
        let error = render_service_diff_migration_sql(&previous.service, &next.service)
            .expect_err("diff should reject destructive changes");

        assert!(error.to_string().contains("manual migration"));
    }

    #[test]
    fn migration_sql_renders_sqlite_bench_example() {
        let loaded = load_service_from_path(&example_path("commerce.eon"))
            .expect("benchmark example should parse");
        let sql =
            render_service_migration_sql(&loaded.service).expect("migration sql should render");

        let account_pos = sql
            .find("CREATE TABLE account")
            .expect("account table should exist");
        let product_pos = sql
            .find("CREATE TABLE product")
            .expect("product table should exist");
        let order_item_pos = sql
            .find("CREATE TABLE sales_order_item")
            .expect("sales_order_item table should exist");

        assert!(account_pos < product_pos);
        assert!(product_pos < order_item_pos);
        assert!(sql.contains("FOREIGN KEY (category_id) REFERENCES category(id)"));
        assert!(sql.contains("FOREIGN KEY (order_id) REFERENCES sales_order(id)"));
        assert!(sql.contains(
            "CREATE INDEX idx_sales_order_item_product_id ON sales_order_item (product_id);"
        ));
        assert!(sql.contains(
            "CREATE INDEX idx_inventory_lot_warehouse_id ON inventory_lot (warehouse_id);"
        ));
    }

    #[test]
    fn migration_sql_renders_policy_example_and_indexes_policy_fields() {
        let loaded = load_service_from_path(&policy_example_path("ops_control.eon"))
            .expect("policy example should parse");
        let sql =
            render_service_migration_sql(&loaded.service).expect("migration sql should render");

        let workspace_pos = sql
            .find("CREATE TABLE workspace")
            .expect("workspace table should exist");
        let project_pos = sql
            .find("CREATE TABLE project")
            .expect("project table should exist");
        let incident_note_pos = sql
            .find("CREATE TABLE incident_note")
            .expect("incident_note table should exist");

        assert!(workspace_pos < project_pos);
        assert!(project_pos < incident_note_pos);
        assert!(sql.contains("FOREIGN KEY (project_id) REFERENCES project(id)"));
        assert!(sql.contains("CREATE INDEX idx_workspace_tenant_id ON workspace (tenant_id);"));
        assert!(
            sql.contains("CREATE INDEX idx_workspace_owner_user_id ON workspace (owner_user_id);")
        );
        assert!(sql.contains(
            "CREATE INDEX idx_on_call_subscription_subscriber_user_id ON on_call_subscription (subscriber_user_id);"
        ));
        assert!(sql.contains(
            "CREATE INDEX idx_audit_export_requested_by_user_id ON audit_export (requested_by_user_id);"
        ));
    }
}
