[package]
name = "rest_macro_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
actix-web.workspace = true
serde.workspace = true
sqlx.workspace = true
serde_json.workspace = true
jsonwebtoken.workspace = true
bcrypt.workspace = true
chrono.workspace = true
dotenv = "0.15.0"
rand.workspace = true
log = { workspace = true }
env_logger = { workspace = true }
rpassword = "7.2"