use actix_web::dev::Payload;
use actix_web::{FromRequest, HttpRequest};
use actix_web::{HttpResponse, Responder, web};
use bcrypt::{hash, verify};
use chrono::{Duration, Utc};
use dotenv::dotenv;
use jsonwebtoken::{DecodingKey, EncodingKey, Header, Validation, decode, encode};
use rand::distr::{Alphanumeric, SampleString};
use rand::rng;
use rpassword;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sqlx::{Column, FromRow, Row, any::AnyRow};
use std::collections::{BTreeMap, HashMap, VecDeque};
use std::env;
use std::future::{Ready, ready};
use std::io::{IsTerminal, Write, stdin, stdout};
use std::sync::{Mutex, OnceLock};
use std::time::{Duration as StdDuration, Instant};

use crate::{
    db::{DbPool, query, query_scalar},
    errors,
    security::{RateLimitRule, SecurityConfig, request_client_ip},
};

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct AuthSettings {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub issuer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audience: Option<String>,
    #[serde(default = "default_access_token_ttl_seconds")]
    pub access_token_ttl_seconds: i64,
}

impl Default for AuthSettings {
    fn default() -> Self {
        Self {
            issuer: None,
            audience: None,
            access_token_ttl_seconds: default_access_token_ttl_seconds(),
        }
    }
}

const fn default_access_token_ttl_seconds() -> i64 {
    24 * 60 * 60
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AuthDbBackend {
    Sqlite,
    Postgres,
    Mysql,
}

impl AuthDbBackend {
    pub fn from_database_url(database_url: &str) -> Option<Self> {
        if database_url.starts_with("postgres:") || database_url.starts_with("postgresql:") {
            Some(Self::Postgres)
        } else if database_url.starts_with("mysql:") || database_url.starts_with("mariadb:") {
            Some(Self::Mysql)
        } else if database_url.starts_with("sqlite:")
            || database_url.starts_with("turso:")
            || database_url.starts_with("turso-local:")
        {
            Some(Self::Sqlite)
        } else {
            None
        }
    }

    fn id_column_sql(self) -> &'static str {
        match self {
            Self::Sqlite => "id INTEGER PRIMARY KEY AUTOINCREMENT",
            Self::Postgres => "id BIGSERIAL PRIMARY KEY",
            Self::Mysql => "id BIGINT AUTO_INCREMENT PRIMARY KEY",
        }
    }

    fn email_column_sql(self) -> &'static str {
        match self {
            Self::Sqlite | Self::Postgres => "email TEXT NOT NULL UNIQUE",
            Self::Mysql => "email VARCHAR(255) NOT NULL UNIQUE",
        }
    }

    fn password_hash_column_sql(self) -> &'static str {
        match self {
            Self::Sqlite | Self::Postgres => "password_hash TEXT NOT NULL",
            Self::Mysql => "password_hash VARCHAR(255) NOT NULL",
        }
    }

    fn role_column_sql(self) -> &'static str {
        match self {
            Self::Sqlite | Self::Postgres => "role TEXT NOT NULL",
            Self::Mysql => "role VARCHAR(64) NOT NULL",
        }
    }
}

pub fn auth_migration_sql(backend: AuthDbBackend) -> String {
    format!(
        "-- Generated by very_simple_rest for built-in auth.\n\n\
         CREATE TABLE user (\n\
             {},\n\
             {},\n\
             {},\n\
             {}\n\
         );\n\n\
         CREATE INDEX idx_user_role ON user (role);\n",
        backend.id_column_sql(),
        backend.email_column_sql(),
        backend.password_hash_column_sql(),
        backend.role_column_sql()
    )
}

// Function to get JWT secret from environment or generate a random one
fn get_jwt_secret() -> &'static [u8] {
    static JWT_SECRET: OnceLock<Vec<u8>> = OnceLock::new();

    JWT_SECRET.get_or_init(|| {
        // Try loading from .env file
        let _ = dotenv();

        // Try to get from environment variable
        match env::var("JWT_SECRET") {
            Ok(secret) => {
                if !secret.is_empty() {
                    return secret.into_bytes();
                }
                // Fall through to random generation if empty
            }
            Err(_) => {
                // Fall through to random generation
            }
        }

        // Generate random secret (32 characters)
        let mut random = rng();
        let random_secret = Alphanumeric.sample_string(&mut random, 32);

        eprintln!("WARNING: No JWT_SECRET found in environment. Using random secret (will change on restart)");
        random_secret.into_bytes()
    }).as_slice()
}

#[derive(Debug, Serialize, Deserialize)]
struct Claims {
    sub: i64,
    roles: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    iss: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    aud: Option<String>,
    exp: usize,
    #[serde(flatten)]
    extra: BTreeMap<String, Value>,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct UserContext {
    pub id: i64,
    pub roles: Vec<String>,
    #[serde(flatten)]
    pub claims: BTreeMap<String, Value>,
}

impl UserContext {
    pub fn claim_i64(&self, claim: &str) -> Option<i64> {
        self.claims.get(claim).and_then(Value::as_i64)
    }
}

impl FromRequest for UserContext {
    type Error = actix_web::Error;
    type Future = Ready<Result<Self, Self::Error>>;

    fn from_request(req: &HttpRequest, _: &mut Payload) -> Self::Future {
        use actix_web::http::header;

        let token = req
            .headers()
            .get(header::AUTHORIZATION)
            .and_then(|h| h.to_str().ok())
            .and_then(|v| v.strip_prefix("Bearer "))
            .map(|s| s.to_string());

        if let Some(token) = token {
            let settings = auth_settings_from_request(req);
            match decode::<Claims>(
                &token,
                &DecodingKey::from_secret(get_jwt_secret()),
                &validation_for_settings(&settings),
            ) {
                Ok(data) => {
                    let claims = data.claims;
                    return ready(Ok(UserContext {
                        id: claims.sub,
                        roles: claims.roles,
                        claims: claims.extra,
                    }));
                }
                Err(_) => {
                    return ready(Err(errors::into_actix_error(errors::unauthorized(
                        "invalid_token",
                        "Invalid token",
                    ))));
                }
            }
        }

        ready(Err(errors::into_actix_error(errors::unauthorized(
            "missing_token",
            "Missing token",
        ))))
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct User {
    pub id: Option<i64>,
    pub email: String,
    pub password_hash: String,
    pub role: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct RegisterInput {
    pub email: String,
    pub password: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct LoginInput {
    pub email: String,
    pub password: String,
}

struct AuthenticatedUser {
    id: i64,
    password_hash: String,
    role: String,
    claims: BTreeMap<String, Value>,
}

#[derive(Default)]
struct AuthRateLimiter {
    entries: Mutex<HashMap<String, VecDeque<Instant>>>,
}

#[derive(Clone, Copy)]
enum AuthRateLimitScope {
    Login,
    Register,
}

impl AuthRateLimitScope {
    fn as_str(self) -> &'static str {
        match self {
            Self::Login => "login",
            Self::Register => "register",
        }
    }
}

pub async fn register(input: web::Json<RegisterInput>, db: web::Data<DbPool>) -> impl Responder {
    register_inner(input, db).await
}

async fn register_inner(input: web::Json<RegisterInput>, db: web::Data<DbPool>) -> HttpResponse {
    let password_hash = match hash(&input.password, 12) {
        Ok(h) => h,
        Err(_) => return errors::internal_error("Hashing error"),
    };

    let result = query("INSERT INTO user (email, password_hash, role) VALUES (?, ?, ?)")
        .bind(&input.email)
        .bind(password_hash)
        .bind("user")
        .execute(db.get_ref())
        .await;

    match result {
        Ok(_) => HttpResponse::Created().finish(),
        Err(error) if is_unique_violation(&error) => {
            errors::conflict("duplicate_email", "A user with that email already exists")
        }
        Err(_) => errors::internal_error("Database error"),
    }
}

pub async fn register_with_request(
    req: HttpRequest,
    input: web::Json<RegisterInput>,
    db: web::Data<DbPool>,
) -> impl Responder {
    if let Some(response) = enforce_auth_rate_limit(&req, AuthRateLimitScope::Register) {
        return response;
    }
    register_inner(input, db).await
}

pub async fn login(input: web::Json<LoginInput>, db: web::Data<DbPool>) -> impl Responder {
    login_with_settings(input, db, AuthSettings::default()).await
}

async fn login_with_settings(
    input: web::Json<LoginInput>,
    db: web::Data<DbPool>,
    settings: AuthSettings,
) -> HttpResponse {
    let user = match load_authenticated_user(db.get_ref(), &input.email).await {
        Ok(Some(user)) => user,
        Ok(None) => return errors::unauthorized("invalid_credentials", "Invalid credentials"),
        Err(_) => return errors::internal_error("Database error"),
    };

    if verify(&input.password, &user.password_hash).unwrap_or(false) {
        let claims = Claims {
            sub: user.id,
            roles: vec![user.role.clone()],
            iss: settings.issuer.clone(),
            aud: settings.audience.clone(),
            exp: (Utc::now() + Duration::seconds(settings.access_token_ttl_seconds)).timestamp()
                as usize,
            extra: user.claims,
        };

        match encode(
            &Header::default(),
            &claims,
            &EncodingKey::from_secret(get_jwt_secret()),
        ) {
            Ok(token) => HttpResponse::Ok().json(serde_json::json!({ "token": token })),
            Err(_) => errors::internal_error("Token generation failed"),
        }
    } else {
        errors::unauthorized("invalid_credentials", "Invalid credentials")
    }
}

pub async fn login_with_request(
    req: HttpRequest,
    input: web::Json<LoginInput>,
    db: web::Data<DbPool>,
) -> impl Responder {
    if let Some(response) = enforce_auth_rate_limit(&req, AuthRateLimitScope::Login) {
        return response;
    }
    let settings = auth_settings_from_request(&req);
    login_with_settings(input, db, settings).await
}

fn is_unique_violation(error: &sqlx::Error) -> bool {
    error
        .as_database_error()
        .map(sqlx::error::DatabaseError::is_unique_violation)
        .unwrap_or(false)
}

async fn load_authenticated_user(
    db: &DbPool,
    email: &str,
) -> Result<Option<AuthenticatedUser>, sqlx::Error> {
    let row = query("SELECT * FROM user WHERE email = ?")
        .bind(email)
        .fetch_optional(db)
        .await?;
    let Some(row) = row else {
        return Ok(None);
    };

    Ok(Some(AuthenticatedUser {
        id: row.try_get("id")?,
        password_hash: row.try_get("password_hash")?,
        role: row.try_get("role")?,
        claims: collect_user_claims(&row)?,
    }))
}

fn collect_user_claims(row: &AnyRow) -> Result<BTreeMap<String, Value>, sqlx::Error> {
    let mut claims = BTreeMap::new();

    for column in row.columns() {
        let column_name = column.name();
        let Some(claim_name) = explicit_claim_name(column_name) else {
            continue;
        };
        if let Some(value) = optional_i64_claim_column(row, column_name)? {
            claims.insert(claim_name, Value::from(value));
        }
    }

    for column in row.columns() {
        let column_name = column.name();
        let Some(claim_name) = implicit_claim_name(column_name) else {
            continue;
        };
        if claims.contains_key(&claim_name) {
            continue;
        }
        if let Some(value) = optional_i64_claim_column(row, column_name)? {
            claims.insert(claim_name, Value::from(value));
        }
    }

    Ok(claims)
}

fn explicit_claim_name(column: &str) -> Option<String> {
    column
        .strip_prefix("claim_")
        .filter(|claim| !claim.is_empty())
        .map(ToOwned::to_owned)
}

fn implicit_claim_name(column: &str) -> Option<String> {
    if matches!(column, "id" | "email" | "password_hash" | "role") {
        return None;
    }
    if column.starts_with("claim_") {
        return None;
    }

    column
        .ends_with("_id")
        .then(|| column.to_owned())
        .filter(|claim| claim != "id")
}

fn optional_i64_claim_column(row: &AnyRow, column: &str) -> Result<Option<i64>, sqlx::Error> {
    match row.try_get::<Option<i64>, _>(column) {
        Ok(value) => Ok(value),
        Err(sqlx::Error::ColumnNotFound(_)) => Ok(None),
        Err(sqlx::Error::ColumnDecode { .. }) => Ok(None),
        Err(error) => Err(error),
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct AdminClaimColumn {
    column_name: String,
    env_var: String,
    required: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct AdminClaimValue {
    column_name: String,
    value: i64,
}

async fn detect_auth_backend(pool: &DbPool) -> Result<AuthDbBackend, sqlx::Error> {
    match pool {
        DbPool::Sqlx(pool) => {
            let connection = pool.acquire().await?;
            let backend_name = connection.backend_name().to_ascii_lowercase();
            if backend_name.contains("postgres") {
                Ok(AuthDbBackend::Postgres)
            } else if backend_name.contains("mysql") {
                Ok(AuthDbBackend::Mysql)
            } else if backend_name.contains("sqlite") {
                Ok(AuthDbBackend::Sqlite)
            } else {
                Err(sqlx::Error::Protocol(format!(
                    "unsupported built-in auth backend `{backend_name}`"
                )))
            }
        }
        #[cfg(feature = "turso-local")]
        DbPool::TursoLocal(_) => Ok(AuthDbBackend::Sqlite),
    }
}

async fn discover_admin_claim_columns(
    pool: &DbPool,
    backend: AuthDbBackend,
) -> Result<Vec<AdminClaimColumn>, sqlx::Error> {
    let rows = match backend {
        AuthDbBackend::Sqlite => query("PRAGMA table_info('user')").fetch_all(pool).await?,
        AuthDbBackend::Postgres => {
            query(
                "SELECT column_name, data_type, is_nullable, column_default \
             FROM information_schema.columns \
             WHERE table_schema = current_schema() AND table_name = 'user' \
             ORDER BY ordinal_position",
            )
            .fetch_all(pool)
            .await?
        }
        AuthDbBackend::Mysql => {
            query(
                "SELECT column_name, data_type, is_nullable, column_default \
             FROM information_schema.columns \
             WHERE table_schema = DATABASE() AND table_name = 'user' \
             ORDER BY ordinal_position",
            )
            .fetch_all(pool)
            .await?
        }
    };

    let mut columns = Vec::new();
    for row in rows {
        let Some(metadata) = admin_claim_column_from_row(&row, backend)? else {
            continue;
        };
        columns.push(metadata);
    }

    Ok(columns)
}

fn admin_claim_column_from_row(
    row: &AnyRow,
    backend: AuthDbBackend,
) -> Result<Option<AdminClaimColumn>, sqlx::Error> {
    let (column_name, data_type, required) = match backend {
        AuthDbBackend::Sqlite => {
            let column_name: String = row.try_get("name")?;
            let data_type: String = row
                .try_get::<Option<String>, _>("type")?
                .unwrap_or_default()
                .to_ascii_lowercase();
            let notnull = row.try_get::<i64, _>("notnull")? != 0;
            let default_value = row.try_get::<Option<String>, _>("dflt_value")?;
            (column_name, data_type, notnull && default_value.is_none())
        }
        AuthDbBackend::Postgres | AuthDbBackend::Mysql => {
            let column_name: String = row.try_get("column_name")?;
            let data_type: String = row.try_get::<String, _>("data_type")?.to_ascii_lowercase();
            let is_nullable = row.try_get::<String, _>("is_nullable")?;
            let default_value = row.try_get::<Option<String>, _>("column_default")?;
            (
                column_name,
                data_type,
                is_nullable.eq_ignore_ascii_case("NO") && default_value.is_none(),
            )
        }
    };

    if !is_admin_claim_column_name(&column_name) || !is_integer_claim_type(&data_type) {
        return Ok(None);
    }

    Ok(Some(AdminClaimColumn {
        env_var: admin_claim_env_var(&column_name),
        column_name,
        required,
    }))
}

fn is_admin_claim_column_name(column_name: &str) -> bool {
    if matches!(column_name, "id" | "email" | "password_hash" | "role") {
        return false;
    }
    if let Some(rest) = column_name.strip_prefix("claim_") {
        return !rest.is_empty();
    }

    column_name.ends_with("_id") && column_name != "id"
}

fn is_integer_claim_type(data_type: &str) -> bool {
    data_type.trim().to_ascii_lowercase().contains("int")
}

fn admin_claim_env_var(column_name: &str) -> String {
    let mut env_var = String::from("ADMIN_");
    for ch in column_name.chars() {
        if ch.is_ascii_alphanumeric() {
            env_var.push(ch.to_ascii_uppercase());
        } else {
            env_var.push('_');
        }
    }
    env_var
}

fn resolve_admin_claim_values(
    claim_columns: &[AdminClaimColumn],
    interactive: bool,
) -> Result<Vec<AdminClaimValue>, String> {
    let mut values = Vec::new();

    for column in claim_columns {
        if let Some(value) = claim_value_from_env(column)? {
            values.push(AdminClaimValue {
                column_name: column.column_name.clone(),
                value,
            });
            continue;
        }

        if interactive {
            if let Some(value) = prompt_admin_claim_value(column)? {
                values.push(AdminClaimValue {
                    column_name: column.column_name.clone(),
                    value,
                });
            }
            continue;
        }

        if column.required {
            return Err(format!(
                "Missing required admin claim column `{}`. Set {} before starting the server.",
                column.column_name, column.env_var
            ));
        }
    }

    Ok(values)
}

fn claim_value_from_env(column: &AdminClaimColumn) -> Result<Option<i64>, String> {
    match std::env::var(&column.env_var) {
        Ok(raw) if raw.trim().is_empty() => Ok(None),
        Ok(raw) => raw.trim().parse::<i64>().map(Some).map_err(|_| {
            format!(
                "Environment variable {} must be a valid integer",
                column.env_var
            )
        }),
        Err(std::env::VarError::NotPresent) => Ok(None),
        Err(error) => Err(format!(
            "Failed to read environment variable {}: {}",
            column.env_var, error
        )),
    }
}

fn prompt_admin_claim_value(column: &AdminClaimColumn) -> Result<Option<i64>, String> {
    let prompt = if column.required {
        format!("{} (required admin claim column): ", column.column_name)
    } else {
        format!(
            "{} (optional admin claim column, press Enter to skip): ",
            column.column_name
        )
    };

    print!("{prompt}");
    stdout()
        .flush()
        .map_err(|error| format!("Failed to flush stdout: {error}"))?;

    let mut value = String::new();
    stdin()
        .read_line(&mut value)
        .map_err(|error| format!("Failed to read {}: {error}", column.column_name))?;

    let value = value.trim();
    if value.is_empty() {
        if column.required {
            return Err(format!("{} is required", column.column_name));
        }
        return Ok(None);
    }

    value
        .parse::<i64>()
        .map(Some)
        .map_err(|_| format!("{} must be a valid integer", column.column_name))
}

fn placeholder_for_backend(backend: AuthDbBackend, index: usize) -> String {
    match backend {
        AuthDbBackend::Postgres => format!("${index}"),
        AuthDbBackend::Sqlite | AuthDbBackend::Mysql => "?".to_owned(),
    }
}

async fn insert_admin_user(
    pool: &DbPool,
    backend: AuthDbBackend,
    email: &str,
    password_hash: &str,
    claim_values: &[AdminClaimValue],
) -> Result<(), sqlx::Error> {
    let mut columns = vec![
        "email".to_owned(),
        "password_hash".to_owned(),
        "role".to_owned(),
    ];
    columns.extend(
        claim_values
            .iter()
            .map(|claim| claim.column_name.clone())
            .collect::<Vec<_>>(),
    );

    let placeholders = (1..=columns.len())
        .map(|index| placeholder_for_backend(backend, index))
        .collect::<Vec<_>>()
        .join(", ");

    let sql = format!(
        "INSERT INTO user ({}) VALUES ({})",
        columns.join(", "),
        placeholders
    );
    let mut query = query(&sql).bind(email).bind(password_hash).bind("admin");
    for claim in claim_values {
        query = query.bind(claim.value);
    }
    query.execute(pool).await?;
    Ok(())
}

pub async fn me(user: UserContext) -> impl Responder {
    HttpResponse::Ok().json(user)
}

/// Check if an admin user exists, and create one automatically if not
///
/// This function will:
/// 1. Check if an admin user already exists
/// 2. If not, prompt the user to enter admin credentials via stdin
///
/// Returns true if an admin exists (either previously or newly created),
/// false only if there was an error creating the admin user.
pub async fn ensure_admin_exists(pool: &DbPool) -> Result<bool, sqlx::Error> {
    ensure_admin_exists_with_claim_prompt_mode(
        pool,
        stdin().is_terminal() && stdout().is_terminal(),
    )
    .await
}

async fn ensure_admin_exists_with_claim_prompt_mode(
    pool: &DbPool,
    interactive_claims: bool,
) -> Result<bool, sqlx::Error> {
    // Check if any admin exists
    let count = match query_scalar::<sqlx::Any, i64>(
        "SELECT COUNT(*) FROM user WHERE role = 'admin'",
    )
    .fetch_one(pool)
    .await
    {
        Ok(count) => count,
        Err(error) => {
            eprintln!(
                "[ERROR] Missing built-in auth schema. Apply the auth migration before starting the server."
            );
            return Err(error);
        }
    };

    let admin_exists = count > 0;

    if admin_exists {
        println!("[INFO] Admin user is set up and ready");
        return Ok(true);
    }

    println!("[INFO] No admin user found. Creating an admin user...");

    // Try to get admin credentials from environment variables first
    let (email, password) = if let (Ok(email), Ok(password)) = (
        std::env::var("ADMIN_EMAIL"),
        std::env::var("ADMIN_PASSWORD"),
    ) {
        if !email.is_empty() && !password.is_empty() {
            println!("[INFO] Using environment variables for admin credentials");
            (email, password)
        } else {
            prompt_admin_credentials()
        }
    } else {
        prompt_admin_credentials()
    };

    // Create the admin user
    let password_hash = match hash(&password, 12) {
        Ok(hash) => hash,
        Err(e) => {
            eprintln!("[ERROR] Failed to hash password: {}", e);
            return Ok(false);
        }
    };
    let backend = match detect_auth_backend(pool).await {
        Ok(backend) => backend,
        Err(error) => {
            eprintln!("[ERROR] Failed to detect auth backend: {}", error);
            return Err(error);
        }
    };
    let claim_columns = match discover_admin_claim_columns(pool, backend).await {
        Ok(columns) => columns,
        Err(error) => {
            eprintln!("[ERROR] Failed to inspect auth schema: {}", error);
            return Err(error);
        }
    };
    let claim_values = match resolve_admin_claim_values(&claim_columns, interactive_claims) {
        Ok(values) => values,
        Err(error) => {
            eprintln!("[ERROR] {}", error);
            return Ok(false);
        }
    };

    let result = insert_admin_user(pool, backend, &email, &password_hash, &claim_values).await;

    match result {
        Ok(_) => {
            println!("[SUCCESS] Admin user created successfully!");
            println!("--------------------------------------------");
            println!("🔐 Admin User Created 🔐");
            println!("Email: {}", email);
            if !claim_values.is_empty() {
                let rendered_claims = claim_values
                    .iter()
                    .map(|claim| format!("{}={}", claim.column_name, claim.value))
                    .collect::<Vec<_>>()
                    .join(", ");
                println!("Claims: {}", rendered_claims);
            }
            println!("--------------------------------------------");
            Ok(true)
        }
        Err(e) => {
            eprintln!("[ERROR] Failed to create admin user: {}", e);
            Ok(false)
        }
    }
}

/// Prompt for admin credentials via stdin
fn prompt_admin_credentials() -> (String, String) {
    println!("[INFO] Please enter admin credentials:");

    // Prompt for email
    let mut email = String::new();
    print!("Admin email: ");
    stdout().flush().unwrap();
    stdin().read_line(&mut email).unwrap();
    let email = email.trim().to_string();

    // Prompt for password securely (no echo)
    let password = match rpassword::prompt_password("Admin password: ") {
        Ok(password) => password,
        Err(e) => {
            eprintln!("[ERROR] Failed to read password: {}", e);
            println!("[WARN] Using default admin credentials as fallback.");
            return create_default_admin();
        }
    };

    // Simple validation
    if email.is_empty() || password.is_empty() {
        println!(
            "[WARN] Email or password cannot be empty. Using default email and a random password."
        );
        return create_default_admin();
    }

    (email, password)
}

/// Create default admin credentials as a fallback
fn create_default_admin() -> (String, String) {
    use rand::RngExt;

    // Characters to use for password generation
    const CHARSET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    // Generate a secure random password
    let mut rng = rand::rng();
    let password: String = (0..12)
        .map(|_| {
            let idx = rng.random_range(0..CHARSET.len());
            CHARSET[idx] as char
        })
        .collect();

    // Use a default admin email
    let email = "admin@example.com".to_string();

    println!("[INFO] Creating default admin user");

    (email, password)
}

pub fn auth_routes(cfg: &mut web::ServiceConfig, db: impl Into<DbPool>) {
    auth_routes_with_settings(cfg, db, AuthSettings::default());
}

pub fn auth_routes_with_settings(
    cfg: &mut web::ServiceConfig,
    db: impl Into<DbPool>,
    settings: AuthSettings,
) {
    let db = web::Data::new(db.into());
    let settings = web::Data::new(settings);
    let limiter = web::Data::new(AuthRateLimiter::default());
    errors::configure_extractor_errors(cfg);
    cfg.app_data(db.clone());
    cfg.app_data(settings.clone());
    cfg.app_data(limiter);

    cfg.route("/auth/register", web::post().to(register_with_request));
    cfg.route("/auth/login", web::post().to(login_with_request));
    cfg.route("/auth/me", web::get().to(me));
}

fn auth_settings_from_request(req: &HttpRequest) -> AuthSettings {
    req.app_data::<web::Data<AuthSettings>>()
        .map(|settings| settings.get_ref().clone())
        .unwrap_or_default()
}

fn security_from_request(req: &HttpRequest) -> SecurityConfig {
    req.app_data::<web::Data<SecurityConfig>>()
        .map(|security| security.get_ref().clone())
        .unwrap_or_else(|| {
            let mut security = SecurityConfig::default();
            security.auth = auth_settings_from_request(req);
            security
        })
}

fn enforce_auth_rate_limit(req: &HttpRequest, scope: AuthRateLimitScope) -> Option<HttpResponse> {
    let security = security_from_request(req);
    let rule = match scope {
        AuthRateLimitScope::Login => security.rate_limits.login,
        AuthRateLimitScope::Register => security.rate_limits.register,
    }?;

    let limiter = req.app_data::<web::Data<AuthRateLimiter>>()?;
    let client_ip = request_client_ip(req, &security)
        .map(|ip| ip.to_string())
        .unwrap_or_else(|| "unknown".to_owned());
    let key = format!("{}:{client_ip}", scope.as_str());
    let retry_after = limiter.check(&key, rule)?;

    let mut response = errors::too_many_requests(
        "rate_limited",
        format!("Too many {} attempts. Try again later.", scope.as_str()),
    );
    if let Ok(value) = actix_web::http::header::HeaderValue::from_str(&retry_after.to_string()) {
        response
            .headers_mut()
            .insert(actix_web::http::header::RETRY_AFTER, value);
    }
    Some(response)
}

fn validation_for_settings(settings: &AuthSettings) -> Validation {
    let mut validation = Validation::default();
    let mut required = vec!["exp"];

    if let Some(audience) = &settings.audience {
        validation.set_audience(&[audience.as_str()]);
        required.push("aud");
    } else {
        validation.validate_aud = false;
    }

    if let Some(issuer) = &settings.issuer {
        validation.set_issuer(&[issuer.as_str()]);
        required.push("iss");
    }

    validation.set_required_spec_claims(&required);
    validation
}

impl AuthRateLimiter {
    fn check(&self, key: &str, rule: RateLimitRule) -> Option<u64> {
        let now = Instant::now();
        let window = StdDuration::from_secs(rule.window_seconds);
        let mut entries = self
            .entries
            .lock()
            .unwrap_or_else(|poison| poison.into_inner());
        let entry = entries.entry(key.to_owned()).or_default();

        while entry
            .front()
            .is_some_and(|instant| now.duration_since(*instant) >= window)
        {
            entry.pop_front();
        }

        if entry.len() >= rule.requests as usize {
            let retry_after = entry
                .front()
                .map(|oldest| {
                    window
                        .saturating_sub(now.duration_since(*oldest))
                        .as_secs()
                        .max(1)
                })
                .unwrap_or(rule.window_seconds);
            return Some(retry_after);
        }

        entry.push_back(now);
        None
    }
}

#[cfg(test)]
mod tests {
    use super::{AuthDbBackend, auth_migration_sql, ensure_admin_exists_with_claim_prompt_mode};
    use crate::database::{DatabaseConfig, DatabaseEngine, TursoLocalConfig};
    use crate::db::{connect, connect_with_config, query, query_scalar};
    use sqlx::Row;
    use std::sync::{Mutex, OnceLock};
    use std::time::{SystemTime, UNIX_EPOCH};

    fn env_lock() -> &'static Mutex<()> {
        static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
        LOCK.get_or_init(|| Mutex::new(()))
    }

    fn unique_sqlite_url(prefix: &str) -> String {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time should be monotonic enough")
            .as_nanos();
        let path = std::env::temp_dir().join(format!("vsr_auth_{prefix}_{nanos}.db"));
        format!("sqlite:{}?mode=rwc", path.display())
    }

    #[test]
    fn sqlite_auth_migration_uses_expected_schema() {
        let sql = auth_migration_sql(AuthDbBackend::Sqlite);
        assert!(sql.contains("CREATE TABLE user"));
        assert!(sql.contains("id INTEGER PRIMARY KEY AUTOINCREMENT"));
        assert!(sql.contains("email TEXT NOT NULL UNIQUE"));
        assert!(sql.contains("password_hash TEXT NOT NULL"));
        assert!(sql.contains("role TEXT NOT NULL"));
        assert!(sql.contains("CREATE INDEX idx_user_role ON user (role);"));
    }

    #[actix_web::test]
    async fn ensure_admin_exists_inserts_detected_claim_columns_from_environment() {
        let _guard = env_lock().lock().unwrap_or_else(|error| error.into_inner());

        unsafe {
            std::env::set_var("ADMIN_EMAIL", "admin@example.com");
            std::env::set_var("ADMIN_PASSWORD", "password123");
            std::env::set_var("ADMIN_TENANT_ID", "7");
            std::env::set_var("ADMIN_CLAIM_WORKSPACE_ID", "42");
        }

        let database_url = unique_sqlite_url("ensure_admin_claims");
        let pool = connect(&database_url)
            .await
            .expect("database should connect");

        query(
            "CREATE TABLE user (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL,
                tenant_id INTEGER,
                claim_workspace_id INTEGER
            )",
        )
        .execute(&pool)
        .await
        .expect("user table should be created");

        let created = ensure_admin_exists_with_claim_prompt_mode(&pool, false)
            .await
            .expect("ensure_admin_exists should not error");
        assert!(created);

        let row = query("SELECT tenant_id, claim_workspace_id FROM user WHERE role = 'admin'")
            .fetch_one(&pool)
            .await
            .expect("admin row should exist");
        let tenant_id: Option<i64> = row.try_get("tenant_id").expect("tenant_id should decode");
        let workspace_id: Option<i64> = row
            .try_get("claim_workspace_id")
            .expect("workspace claim should decode");
        assert_eq!(tenant_id, Some(7));
        assert_eq!(workspace_id, Some(42));

        unsafe {
            std::env::remove_var("ADMIN_EMAIL");
            std::env::remove_var("ADMIN_PASSWORD");
            std::env::remove_var("ADMIN_TENANT_ID");
            std::env::remove_var("ADMIN_CLAIM_WORKSPACE_ID");
        }
    }

    #[actix_web::test]
    async fn ensure_admin_exists_returns_false_when_required_claim_is_missing() {
        let _guard = env_lock().lock().unwrap_or_else(|error| error.into_inner());

        unsafe {
            std::env::set_var("ADMIN_EMAIL", "admin@example.com");
            std::env::set_var("ADMIN_PASSWORD", "password123");
            std::env::remove_var("ADMIN_TENANT_ID");
        }

        let database_url = unique_sqlite_url("ensure_admin_required_claim");
        let pool = connect(&database_url)
            .await
            .expect("database should connect");

        query(
            "CREATE TABLE user (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL,
                tenant_id INTEGER NOT NULL
            )",
        )
        .execute(&pool)
        .await
        .expect("user table should be created");

        let created = ensure_admin_exists_with_claim_prompt_mode(&pool, false)
            .await
            .expect("ensure_admin_exists should not error");
        assert!(!created);

        let count: i64 = query_scalar::<sqlx::Any, i64>("SELECT COUNT(*) FROM user")
            .fetch_one(&pool)
            .await
            .expect("row count should be queryable");
        assert_eq!(count, 0);

        unsafe {
            std::env::remove_var("ADMIN_EMAIL");
            std::env::remove_var("ADMIN_PASSWORD");
        }
    }

    #[cfg(feature = "turso-local")]
    #[actix_web::test]
    async fn ensure_admin_exists_works_with_encrypted_turso_local() {
        let _guard = env_lock().lock().unwrap_or_else(|error| error.into_inner());
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time should be monotonic enough")
            .as_nanos();
        let path = std::env::temp_dir().join(format!("vsr_auth_encrypted_{stamp}.db"));
        let env_var = format!("VSR_AUTH_TURSO_KEY_{stamp}");
        let key = "c1bbfda4f589dc9daaf004fe21111e00dc00c98237102f5c7002a5669fc76327";

        unsafe {
            std::env::set_var("ADMIN_EMAIL", "encrypted-admin@example.com");
            std::env::set_var("ADMIN_PASSWORD", "password123");
            std::env::set_var(&env_var, key);
        }

        let config = DatabaseConfig {
            engine: DatabaseEngine::TursoLocal(TursoLocalConfig {
                path: path.to_string_lossy().into_owned(),
                encryption_key_env: Some(env_var.clone()),
            }),
        };
        let pool = connect_with_config("sqlite:ignored.db?mode=rwc", &config)
            .await
            .expect("database should connect");

        for statement in auth_migration_sql(AuthDbBackend::Sqlite)
            .split(';')
            .map(str::trim)
            .filter(|statement| !statement.is_empty())
        {
            query(statement)
                .execute(&pool)
                .await
                .expect("auth schema should apply");
        }

        let created = ensure_admin_exists_with_claim_prompt_mode(&pool, false)
            .await
            .expect("ensure_admin_exists should not error");
        assert!(created);

        let count: i64 =
            query_scalar::<sqlx::Any, i64>("SELECT COUNT(*) FROM user WHERE role = 'admin'")
                .fetch_one(&pool)
                .await
                .expect("admin row should be queryable");
        assert_eq!(count, 1);

        unsafe {
            std::env::remove_var("ADMIN_EMAIL");
            std::env::remove_var("ADMIN_PASSWORD");
            std::env::remove_var(&env_var);
        }
        let _ = std::fs::remove_file(path);
    }
}
