//! Compiler-independent database, relation, action, audit, and computed-field metadata.

use serde_json::Value as JsonValue;

/// Structured scalar represented by a service field.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StructuredScalarKind {
    /// Date and time with an offset.
    DateTime,
    /// Calendar date.
    Date,
    /// Time of day.
    Time,
    /// UUID value.
    Uuid,
    /// Decimal value.
    Decimal,
    /// Arbitrary JSON value.
    Json,
    /// JSON object.
    JsonObject,
    /// JSON array.
    JsonArray,
}

impl StructuredScalarKind {
    /// SQL storage type for this scalar on a database backend.
    pub fn sql_type(self, db: DbBackend) -> &'static str {
        match (self, db) {
            (_, DbBackend::Sqlite | DbBackend::Postgres) => "TEXT",
            (Self::DateTime, DbBackend::Mysql) => "VARCHAR(64)",
            (Self::Date, DbBackend::Mysql) => "VARCHAR(10)",
            (Self::Time, DbBackend::Mysql) => "VARCHAR(15)",
            (Self::Uuid, DbBackend::Mysql) => "CHAR(36)",
            (Self::Decimal, DbBackend::Mysql) => "VARCHAR(80)",
            (Self::Json | Self::JsonObject | Self::JsonArray, DbBackend::Mysql) => "TEXT",
        }
    }

    /// OpenAPI format label, when a scalar has one.
    pub fn openapi_format(self) -> Option<&'static str> {
        match self {
            Self::DateTime => Some("date-time"),
            Self::Date => Some("date"),
            Self::Time => Some("time"),
            Self::Uuid => Some("uuid"),
            Self::Decimal => Some("decimal"),
            Self::Json | Self::JsonObject | Self::JsonArray => None,
        }
    }

    /// Whether range filters are defined for this scalar.
    pub fn supports_range_filters(self) -> bool {
        matches!(self, Self::DateTime | Self::Date | Self::Time)
    }

    /// Whether the scalar supports ordering.
    pub fn supports_sort(self) -> bool {
        !matches!(
            self,
            Self::Decimal | Self::Json | Self::JsonObject | Self::JsonArray
        )
    }

    /// Whether equality filters are defined for this scalar.
    pub fn supports_exact_filters(self) -> bool {
        !matches!(self, Self::Json | Self::JsonObject | Self::JsonArray)
    }

    /// Temporal kind to use when this scalar is database-generated.
    pub fn generated_temporal_kind(self) -> Option<GeneratedTemporalKind> {
        match self {
            Self::DateTime => Some(GeneratedTemporalKind::DateTime),
            Self::Date => Some(GeneratedTemporalKind::Date),
            Self::Time => Some(GeneratedTemporalKind::Time),
            Self::Uuid | Self::Decimal | Self::Json | Self::JsonObject | Self::JsonArray => None,
        }
    }
}

/// Type of temporal value generated by the database.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GeneratedTemporalKind {
    /// Date and time.
    DateTime,
    /// Calendar date.
    Date,
    /// Time of day.
    Time,
}

/// Database dialect used by runtime SQL and service schema generation.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, serde::Deserialize)]
pub enum DbBackend {
    /// SQLite or a compatible embedded database.
    #[default]
    Sqlite,
    /// PostgreSQL.
    Postgres,
    /// MySQL.
    Mysql,
}

impl DbBackend {
    /// Positional bind placeholder for the backend.
    pub fn placeholder(self, index: usize) -> String {
        match self {
            Self::Postgres => format!("${index}"),
            Self::Sqlite | Self::Mysql => "?".to_owned(),
        }
    }

    /// SQL declaration for an auto-incrementing primary key.
    pub fn primary_key_sql(self, field_name: &str) -> String {
        match self {
            Self::Sqlite => format!("{field_name} INTEGER PRIMARY KEY AUTOINCREMENT"),
            Self::Postgres => format!("{field_name} BIGSERIAL PRIMARY KEY"),
            Self::Mysql => format!("{field_name} BIGINT AUTO_INCREMENT PRIMARY KEY"),
        }
    }

    /// SQL expression used to generate a temporal field value.
    pub fn generated_temporal_expression(
        self,
        kind: Option<GeneratedTemporalKind>,
    ) -> &'static str {
        match kind {
            Some(GeneratedTemporalKind::DateTime) => match self {
                Self::Sqlite => "(STRFTIME('%Y-%m-%dT%H:%M:%f000+00:00', 'now'))",
                Self::Postgres => {
                    "(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.US') || '+00:00')"
                }
                Self::Mysql => "(DATE_FORMAT(UTC_TIMESTAMP(6), '%Y-%m-%dT%H:%i:%s.%f+00:00'))",
            },
            Some(GeneratedTemporalKind::Date) => match self {
                Self::Sqlite => "(DATE('now'))",
                Self::Postgres => "(TO_CHAR(CURRENT_DATE, 'YYYY-MM-DD'))",
                Self::Mysql => "(DATE_FORMAT(UTC_DATE(), '%Y-%m-%d'))",
            },
            Some(GeneratedTemporalKind::Time) => match self {
                Self::Sqlite => "(STRFTIME('%H:%M:%f000', 'now'))",
                Self::Postgres => {
                    "(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'HH24:MI:SS.US'))"
                }
                Self::Mysql => "(DATE_FORMAT(UTC_TIMESTAMP(6), '%H:%i:%s.%f'))",
            },
            None => "CURRENT_TIMESTAMP",
        }
    }
}
/// Foreign-key relation declared on a field.
#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct RelationSpec {
    /// Target table.
    pub references_table: String,
    /// Target field.
    pub references_field: String,
    /// Action when the target row is deleted.
    #[serde(default)]
    pub on_delete: Option<ReferentialAction>,
    /// Whether to expose a nested collection route.
    #[serde(default)]
    pub nested_route: bool,
}

/// Referential action on a deleted foreign-key target.
#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum ReferentialAction {
    /// Delete referencing rows.
    Cascade,
    /// Refuse the deletion.
    Restrict,
    /// Set the reference to NULL.
    SetNull,
    /// Leave the reference unchanged.
    NoAction,
}

impl ReferentialAction {
    /// Parse an action from its service-schema spelling.
    pub fn parse(value: &str) -> Option<Self> {
        match value.trim().to_ascii_lowercase().as_str() {
            "cascade" => Some(Self::Cascade),
            "restrict" => Some(Self::Restrict),
            "set_null" | "setnull" | "set-null" => Some(Self::SetNull),
            "no_action" | "noaction" | "no-action" => Some(Self::NoAction),
            _ => None,
        }
    }

    /// SQL keyword for the action.
    pub fn sql(self) -> &'static str {
        match self {
            Self::Cascade => "CASCADE",
            Self::Restrict => "RESTRICT",
            Self::SetNull => "SET NULL",
            Self::NoAction => "NO ACTION",
        }
    }
}

/// Named projection of response fields.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ResponseContextSpec {
    /// Context name exposed to callers.
    pub name: String,
    /// Public field names included in the response.
    pub fields: Vec<String>,
}

/// Named enumeration and its accepted values.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EnumSpec {
    /// Enumeration name.
    pub name: String,
    /// Accepted values.
    pub values: Vec<String>,
}

/// Database index declared for a resource.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct IndexSpec {
    /// Indexed field names.
    pub fields: Vec<String>,
    /// Whether indexed values must be unique.
    pub unique: bool,
}

impl IndexSpec {
    /// Generate the index name for a table.
    pub fn name_for_table(&self, table_name: &str) -> String {
        let prefix = if self.unique { "uidx" } else { "idx" };
        format!("{prefix}_{table_name}_{}", self.fields.join("_"))
    }
}

/// Many-to-many relation backed by a join table.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ManyToManySpec {
    /// Public relation name.
    pub name: String,
    /// Target resource table.
    pub target_table: String,
    /// Join table.
    pub through_table: String,
    /// Join-table field referring to the source.
    pub source_field: String,
    /// Join-table field referring to the target.
    pub target_field: String,
}

/// Resource instance targeted by a custom action.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ResourceActionTarget {
    /// A single item.
    Item,
}

/// HTTP method used by a custom resource action.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ResourceActionMethod {
    /// POST request.
    Post,
}

/// Source of a value assigned by a custom action.
#[derive(Clone, Debug, PartialEq)]
pub enum ResourceActionValueSpec {
    /// Fixed JSON value.
    Literal(JsonValue),
    /// Named action input field.
    InputField(String),
}

/// Public input field accepted by a custom action.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ResourceActionInputFieldSpec {
    /// Input name.
    pub name: String,
    /// Resource field receiving the value.
    pub target_field: String,
}

/// Assignment performed by a custom action.
#[derive(Clone, Debug, PartialEq)]
pub struct ResourceActionAssignmentSpec {
    /// Resource field receiving the value.
    pub field: String,
    /// Value assigned to that field.
    pub value: ResourceActionValueSpec,
}

/// Write operation performed by a custom action.
#[derive(Clone, Debug, PartialEq)]
pub enum ResourceActionBehaviorSpec {
    /// Update selected fields.
    UpdateFields {
        /// Assignments applied to the selected item.
        assignments: Vec<ResourceActionAssignmentSpec>,
    },
    /// Delete the selected item.
    DeleteResource,
}

/// Custom action exposed on a resource item.
#[derive(Clone, Debug, PartialEq)]
pub struct ResourceActionSpec {
    /// Public action name.
    pub name: String,
    /// Route suffix.
    pub path: String,
    /// Resource instance targeted by the action.
    pub target: ResourceActionTarget,
    /// HTTP method used by the route.
    pub method: ResourceActionMethod,
    /// Accepted request fields.
    pub input_fields: Vec<ResourceActionInputFieldSpec>,
    /// Write operation performed by the action.
    pub behavior: ResourceActionBehaviorSpec,
}

/// Which custom actions produce audit events.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ResourceAuditActionSelection {
    /// Audit all custom actions.
    All,
    /// Audit only named actions.
    Named(Vec<String>),
}

impl ResourceAuditActionSelection {
    /// Whether the named action must be audited.
    pub fn audits_action(&self, action_name: &str) -> bool {
        match self {
            Self::All => true,
            Self::Named(actions) => actions.iter().any(|candidate| candidate == action_name),
        }
    }
}

/// Audit events emitted by a resource.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ResourceAuditConfig {
    /// Resource receiving audit events.
    pub resource: String,
    /// Audit creation.
    pub create: bool,
    /// Audit updates.
    pub update: bool,
    /// Audit deletion.
    pub delete: bool,
    /// Optional custom action selection.
    pub actions: Option<ResourceAuditActionSelection>,
}

impl ResourceAuditConfig {
    /// Whether creation is audited.
    pub fn audits_create(&self) -> bool {
        self.create
    }

    /// Whether updates are audited.
    pub fn audits_update(&self) -> bool {
        self.update
    }

    /// Whether deletion is audited.
    pub fn audits_delete(&self) -> bool {
        self.delete
    }

    /// Whether the named custom action is audited.
    pub fn audits_action(&self, action_name: &str) -> bool {
        self.actions
            .as_ref()
            .is_some_and(|selection| selection.audits_action(action_name))
    }

    /// Whether the resource emits any audit event.
    pub fn is_enabled(&self) -> bool {
        self.create || self.update || self.delete || self.actions.is_some()
    }
}

/// Part of a computed text field.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ComputedFieldPart {
    /// Fixed text.
    Literal(String),
    /// Value read from a stored field.
    Field(String),
}

/// Public field computed from other field values.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ComputedFieldSpec {
    /// Public field name.
    pub api_name: String,
    /// Whether absent source values are accepted.
    pub optional: bool,
    /// Ordered parts that form the computed value.
    pub parts: Vec<ComputedFieldPart>,
}

#[cfg(test)]
mod tests {
    use super::{
        DbBackend, GeneratedTemporalKind, ResourceAuditActionSelection, ResourceAuditConfig,
    };

    #[test]
    fn backend_sql_and_audit_selection_keep_runtime_semantics() {
        assert_eq!(DbBackend::Postgres.placeholder(3), "$3");
        assert_eq!(DbBackend::Sqlite.placeholder(3), "?");
        assert_eq!(
            DbBackend::Mysql.primary_key_sql("id"),
            "id BIGINT AUTO_INCREMENT PRIMARY KEY"
        );
        assert!(
            DbBackend::Postgres
                .generated_temporal_expression(Some(GeneratedTemporalKind::DateTime))
                .contains("AT TIME ZONE 'UTC'")
        );

        let audit = ResourceAuditConfig {
            resource: "events".into(),
            create: false,
            update: true,
            delete: false,
            actions: Some(ResourceAuditActionSelection::Named(vec!["publish".into()])),
        };
        assert!(audit.is_enabled());
        assert!(audit.audits_update());
        assert!(audit.audits_action("publish"));
        assert!(!audit.audits_action("archive"));
    }
}
